server:
  port: 8082 # inside container port

spring:
  profiles:
    include: 'secret'

auth:
  header: Id-Token

terraform:
  service:
    server: 127.0.0.1
    port: 8084

firebase:
  admin:
    sdk:
      key: # EMPTY - locally use application-secret.yml to override or provide json file
      json: serviceAccountKey.json
