server:
  port: 8082 # inside container port

spring:
  profiles:
    include: 'secret'

auth:
  header: Id-Token

firebase:
  admin:
    sdk:
      key: # EMPTY - locally use application-secret.yml to override or provide json file
      json: serviceAccountKey.json
