---
name: Build and Push auth-code Microservice to GCR
on:
  push:
    branches: [ master ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: auth-service
      PROJECT_ID: qrcode-374515

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/772208948259/locations/global/workloadIdentityPools/github-auth-action-pool/providers/gh-actions-auth-provider'
        service_account: 'github-actions-qrcode@qrcode-374515.iam.gserviceaccount.com'

    - name: Echo Firebase SDK
      run: echo ${{ secrets.FIREBASE_ADMIN_SDK_KEY }}

    # Special Build step with a custom action for passing down GitHub's secret
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./auth
        tags: ${{ env.IMAGE_NAME }}:latest
        build-args: |
          "GOOGLE_CLOUD_IDENTITY_PLATFORM_API_KEY=${{ secrets.GOOGLE_CLOUD_IDENTITY_PLATFORM_API_KEY }}"
# "FIREBASE_ADMIN_SDK_KEY=${{ secrets.FIREBASE_ADMIN_SDK_KEY }}"

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
    
    - name: Push Docker Image to GCR
      run: |-
        docker tag $IMAGE_NAME:latest eu.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push eu.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
